export const DELETE_FAVORITE = "DELETE_FAVORITE"
export const ADD_FAVORITE = "ADD_FAVORITE"
export const FETCH_LAUNCHES = "FETCH_LAUNCHES"
export const FETCH_LAUNCHES_SUCCESS = "FETCH_LAUNCHES_SUCCESS"
export const FETCH_LAUNCHES_FAIL = "FETCH_LAUNCHES_FAIL"
export const GET_LAUNCH_INFO = 'GET_LAUNCH_INFO'
export const GET_LAUNCH_INFO_SUCCESS = 'GET_LAUNCH_INFO_SUCCESS'
export const GET_LAUNCH_INFO_FAIL = 'GET_LAUNCH_INFO_FAIL'